/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 11
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 116
#define ALIAS_COUNT 0
#define TOKEN_COUNT 107
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_fn = 3,
  anon_sym_if = 4,
  anon_sym_elif = 5,
  anon_sym_else = 6,
  anon_sym_for = 7,
  anon_sym_while = 8,
  anon_sym_in = 9,
  anon_sym_match = 10,
  anon_sym_select = 11,
  anon_sym_parallel = 12,
  anon_sym_spawn = 13,
  anon_sym_return = 14,
  anon_sym_break = 15,
  anon_sym_continue = 16,
  anon_sym_or_return = 17,
  anon_sym_struct = 18,
  anon_sym_enum = 19,
  anon_sym_type = 20,
  anon_sym_import = 21,
  anon_sym_package = 22,
  anon_sym_extern = 23,
  anon_sym_inout = 24,
  anon_sym_soa = 25,
  anon_sym_and = 26,
  anon_sym_or = 27,
  anon_sym_not = 28,
  anon_sym_true = 29,
  anon_sym_false = 30,
  anon_sym_null = 31,
  anon_sym_int = 32,
  anon_sym_float = 33,
  anon_sym_string = 34,
  anon_sym_bool = 35,
  anon_sym_char = 36,
  anon_sym_ptr = 37,
  anon_sym_void = 38,
  anon_sym_print = 39,
  anon_sym_println = 40,
  anon_sym_str = 41,
  anon_sym_len = 42,
  anon_sym_push = 43,
  anon_sym_pop = 44,
  anon_sym_range = 45,
  anon_sym_split = 46,
  anon_sym_substr = 47,
  anon_sym_find = 48,
  anon_sym_read_file = 49,
  anon_sym_write_file = 50,
  anon_sym_read_all = 51,
  anon_sym_list_dir = 52,
  anon_sym_args = 53,
  anon_sym_getenv = 54,
  anon_sym_input = 55,
  anon_sym_chr = 56,
  anon_sym_die = 57,
  anon_sym_is_null = 58,
  anon_sym_sqrt = 59,
  anon_sym_pow = 60,
  anon_sym_floor = 61,
  anon_sym_fabs = 62,
  anon_sym_map_get = 63,
  anon_sym_map_set = 64,
  anon_sym_reserve = 65,
  sym_number = 66,
  sym_string = 67,
  sym_fstring = 68,
  sym_char = 69,
  anon_sym_COLON_EQ = 70,
  anon_sym_DASH_GT = 71,
  anon_sym_EQ_EQ = 72,
  anon_sym_BANG_EQ = 73,
  anon_sym_LT_EQ = 74,
  anon_sym_GT_EQ = 75,
  anon_sym_LT_LT = 76,
  anon_sym_GT_GT = 77,
  anon_sym_PLUS_EQ = 78,
  anon_sym_DASH_EQ = 79,
  anon_sym_STAR_EQ = 80,
  anon_sym_SLASH_EQ = 81,
  anon_sym_PERCENT_EQ = 82,
  anon_sym_AMP_EQ = 83,
  anon_sym_PIPE_EQ = 84,
  anon_sym_CARET_EQ = 85,
  anon_sym_PLUS = 86,
  anon_sym_DASH = 87,
  anon_sym_STAR = 88,
  anon_sym_SLASH = 89,
  anon_sym_PERCENT = 90,
  anon_sym_LT = 91,
  anon_sym_GT = 92,
  anon_sym_EQ = 93,
  anon_sym_AMP = 94,
  anon_sym_PIPE = 95,
  anon_sym_CARET = 96,
  anon_sym_TILDE = 97,
  anon_sym_DOT = 98,
  anon_sym_LPAREN = 99,
  anon_sym_RPAREN = 100,
  anon_sym_LBRACK = 101,
  anon_sym_RBRACK = 102,
  anon_sym_LBRACE = 103,
  anon_sym_RBRACE = 104,
  anon_sym_COMMA = 105,
  anon_sym_COLON = 106,
  sym_source_file = 107,
  sym__token = 108,
  sym_keyword = 109,
  sym_constant = 110,
  sym_type = 111,
  sym_builtin = 112,
  sym_operator = 113,
  sym_punctuation = 114,
  aux_sym_source_file_repeat1 = 115,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_fn] = "fn",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_while] = "while",
  [anon_sym_in] = "in",
  [anon_sym_match] = "match",
  [anon_sym_select] = "select",
  [anon_sym_parallel] = "parallel",
  [anon_sym_spawn] = "spawn",
  [anon_sym_return] = "return",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_or_return] = "or_return",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [anon_sym_type] = "type",
  [anon_sym_import] = "import",
  [anon_sym_package] = "package",
  [anon_sym_extern] = "extern",
  [anon_sym_inout] = "inout",
  [anon_sym_soa] = "soa",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_not] = "not",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_null] = "null",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_string] = "string",
  [anon_sym_bool] = "bool",
  [anon_sym_char] = "char",
  [anon_sym_ptr] = "ptr",
  [anon_sym_void] = "void",
  [anon_sym_print] = "print",
  [anon_sym_println] = "println",
  [anon_sym_str] = "str",
  [anon_sym_len] = "len",
  [anon_sym_push] = "push",
  [anon_sym_pop] = "pop",
  [anon_sym_range] = "range",
  [anon_sym_split] = "split",
  [anon_sym_substr] = "substr",
  [anon_sym_find] = "find",
  [anon_sym_read_file] = "read_file",
  [anon_sym_write_file] = "write_file",
  [anon_sym_read_all] = "read_all",
  [anon_sym_list_dir] = "list_dir",
  [anon_sym_args] = "args",
  [anon_sym_getenv] = "getenv",
  [anon_sym_input] = "input",
  [anon_sym_chr] = "chr",
  [anon_sym_die] = "die",
  [anon_sym_is_null] = "is_null",
  [anon_sym_sqrt] = "sqrt",
  [anon_sym_pow] = "pow",
  [anon_sym_floor] = "floor",
  [anon_sym_fabs] = "fabs",
  [anon_sym_map_get] = "map_get",
  [anon_sym_map_set] = "map_set",
  [anon_sym_reserve] = "reserve",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_fstring] = "fstring",
  [sym_char] = "char",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_PERCENT_EQ] = "%=",
  [anon_sym_AMP_EQ] = "&=",
  [anon_sym_PIPE_EQ] = "|=",
  [anon_sym_CARET_EQ] = "^=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET] = "^",
  [anon_sym_TILDE] = "~",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym__token] = "_token",
  [sym_keyword] = "keyword",
  [sym_constant] = "constant",
  [sym_type] = "type",
  [sym_builtin] = "builtin",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_select] = anon_sym_select,
  [anon_sym_parallel] = anon_sym_parallel,
  [anon_sym_spawn] = anon_sym_spawn,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_or_return] = anon_sym_or_return,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_inout] = anon_sym_inout,
  [anon_sym_soa] = anon_sym_soa,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_ptr] = anon_sym_ptr,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_println] = anon_sym_println,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_len] = anon_sym_len,
  [anon_sym_push] = anon_sym_push,
  [anon_sym_pop] = anon_sym_pop,
  [anon_sym_range] = anon_sym_range,
  [anon_sym_split] = anon_sym_split,
  [anon_sym_substr] = anon_sym_substr,
  [anon_sym_find] = anon_sym_find,
  [anon_sym_read_file] = anon_sym_read_file,
  [anon_sym_write_file] = anon_sym_write_file,
  [anon_sym_read_all] = anon_sym_read_all,
  [anon_sym_list_dir] = anon_sym_list_dir,
  [anon_sym_args] = anon_sym_args,
  [anon_sym_getenv] = anon_sym_getenv,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_chr] = anon_sym_chr,
  [anon_sym_die] = anon_sym_die,
  [anon_sym_is_null] = anon_sym_is_null,
  [anon_sym_sqrt] = anon_sym_sqrt,
  [anon_sym_pow] = anon_sym_pow,
  [anon_sym_floor] = anon_sym_floor,
  [anon_sym_fabs] = anon_sym_fabs,
  [anon_sym_map_get] = anon_sym_map_get,
  [anon_sym_map_set] = anon_sym_map_set,
  [anon_sym_reserve] = anon_sym_reserve,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_fstring] = sym_fstring,
  [sym_char] = sym_char,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_PERCENT_EQ] = anon_sym_PERCENT_EQ,
  [anon_sym_AMP_EQ] = anon_sym_AMP_EQ,
  [anon_sym_PIPE_EQ] = anon_sym_PIPE_EQ,
  [anon_sym_CARET_EQ] = anon_sym_CARET_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym__token] = sym__token,
  [sym_keyword] = sym_keyword,
  [sym_constant] = sym_constant,
  [sym_type] = sym_type,
  [sym_builtin] = sym_builtin,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_select] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_parallel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spawn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_soa] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ptr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_println] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_len] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_push] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_range] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_split] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_substr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_find] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_read_file] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_write_file] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_read_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list_dir] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_args] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_getenv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_chr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_die] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sqrt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_floor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fabs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reserve] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_fstring] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 4,
        '"', 1,
        '#', 11,
        '%', 39,
        '&', 43,
        '\'', 5,
        '(', 48,
        ')', 49,
        '*', 37,
        '+', 35,
        ',', 54,
        '-', 36,
        '.', 47,
        '/', 38,
        ':', 55,
        '<', 40,
        '=', 42,
        '>', 41,
        '[', 50,
        ']', 51,
        '^', 45,
        'f', 12,
        '{', 52,
        '|', 44,
        '}', 53,
        '~', 46,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(3);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_fstring);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AMP_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_CARET_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(20);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_CARET);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'g', 7,
        'i', 8,
        'l', 9,
        'm', 10,
        'n', 11,
        'o', 12,
        'p', 13,
        'r', 14,
        's', 15,
        't', 16,
        'v', 17,
        'w', 18,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(21);
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == 'h') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == 'l') ADVANCE(31);
      if (lookahead == 'n') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(35);
      if (lookahead == 'm') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(37);
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(39);
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(42);
      if (lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(45);
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead == 'r') ADVANCE(47);
      if (lookahead == 't') ADVANCE(48);
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(50);
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead == 'o') ADVANCE(53);
      if (lookahead == 'p') ADVANCE(54);
      if (lookahead == 'q') ADVANCE(55);
      if (lookahead == 't') ADVANCE(56);
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == 'y') ADVANCE(59);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(61);
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(63);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(64);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(65);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(67);
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(71);
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(73);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 29:
      if (lookahead == 'b') ADVANCE(75);
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(78);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 36:
      if (lookahead == 'p') ADVANCE(81);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'o') ADVANCE(82);
      if (lookahead == 'p') ADVANCE(83);
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 38:
      if (lookahead == '_') ADVANCE(85);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(86);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(87);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(88);
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(91);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_or);
      if (lookahead == '_') ADVANCE(92);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(93);
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 46:
      if (lookahead == 'p') ADVANCE(95);
      if (lookahead == 'w') ADVANCE(96);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(97);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(98);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead == 's') ADVANCE(102);
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(104);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(105);
      END_STATE();
    case 54:
      if (lookahead == 'a') ADVANCE(106);
      if (lookahead == 'l') ADVANCE(107);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(108);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(109);
      END_STATE();
    case 57:
      if (lookahead == 'b') ADVANCE(110);
      END_STATE();
    case 58:
      if (lookahead == 'u') ADVANCE(111);
      END_STATE();
    case 59:
      if (lookahead == 'p') ADVANCE(112);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(113);
      END_STATE();
    case 61:
      if (lookahead == 'i') ADVANCE(114);
      END_STATE();
    case 62:
      if (lookahead == 'i') ADVANCE(115);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(116);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(117);
      END_STATE();
    case 66:
      if (lookahead == 'a') ADVANCE(118);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(119);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_chr);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(120);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_die);
      END_STATE();
    case 71:
      if (lookahead == 'f') ADVANCE(121);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 73:
      if (lookahead == 'm') ADVANCE(123);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(124);
      END_STATE();
    case 75:
      if (lookahead == 's') ADVANCE(125);
      END_STATE();
    case 76:
      if (lookahead == 's') ADVANCE(126);
      END_STATE();
    case 77:
      if (lookahead == 'd') ADVANCE(127);
      END_STATE();
    case 78:
      if (lookahead == 'a') ADVANCE(128);
      if (lookahead == 'o') ADVANCE(129);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 80:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 81:
      if (lookahead == 'o') ADVANCE(131);
      END_STATE();
    case 82:
      if (lookahead == 'u') ADVANCE(132);
      END_STATE();
    case 83:
      if (lookahead == 'u') ADVANCE(133);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 85:
      if (lookahead == 'n') ADVANCE(134);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_len);
      END_STATE();
    case 87:
      if (lookahead == 't') ADVANCE(135);
      END_STATE();
    case 88:
      if (lookahead == '_') ADVANCE(136);
      END_STATE();
    case 89:
      if (lookahead == 'c') ADVANCE(137);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 91:
      if (lookahead == 'l') ADVANCE(138);
      END_STATE();
    case 92:
      if (lookahead == 'r') ADVANCE(139);
      END_STATE();
    case 93:
      if (lookahead == 'k') ADVANCE(140);
      END_STATE();
    case 94:
      if (lookahead == 'a') ADVANCE(141);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_pop);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_pow);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(142);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_ptr);
      END_STATE();
    case 99:
      if (lookahead == 'h') ADVANCE(143);
      END_STATE();
    case 100:
      if (lookahead == 'g') ADVANCE(144);
      END_STATE();
    case 101:
      if (lookahead == 'd') ADVANCE(145);
      END_STATE();
    case 102:
      if (lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 103:
      if (lookahead == 'u') ADVANCE(147);
      END_STATE();
    case 104:
      if (lookahead == 'e') ADVANCE(148);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_soa);
      END_STATE();
    case 106:
      if (lookahead == 'w') ADVANCE(149);
      END_STATE();
    case 107:
      if (lookahead == 'i') ADVANCE(150);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(151);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_str);
      if (lookahead == 'i') ADVANCE(152);
      if (lookahead == 'u') ADVANCE(153);
      END_STATE();
    case 110:
      if (lookahead == 's') ADVANCE(154);
      END_STATE();
    case 111:
      if (lookahead == 'e') ADVANCE(155);
      END_STATE();
    case 112:
      if (lookahead == 'e') ADVANCE(156);
      END_STATE();
    case 113:
      if (lookahead == 'd') ADVANCE(157);
      END_STATE();
    case 114:
      if (lookahead == 'l') ADVANCE(158);
      END_STATE();
    case 115:
      if (lookahead == 't') ADVANCE(159);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_args);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 118:
      if (lookahead == 'k') ADVANCE(160);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 120:
      if (lookahead == 'i') ADVANCE(161);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 124:
      if (lookahead == 'r') ADVANCE(162);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_fabs);
      END_STATE();
    case 126:
      if (lookahead == 'e') ADVANCE(163);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_find);
      END_STATE();
    case 128:
      if (lookahead == 't') ADVANCE(164);
      END_STATE();
    case 129:
      if (lookahead == 'r') ADVANCE(165);
      END_STATE();
    case 130:
      if (lookahead == 'n') ADVANCE(166);
      END_STATE();
    case 131:
      if (lookahead == 'r') ADVANCE(167);
      END_STATE();
    case 132:
      if (lookahead == 't') ADVANCE(168);
      END_STATE();
    case 133:
      if (lookahead == 't') ADVANCE(169);
      END_STATE();
    case 134:
      if (lookahead == 'u') ADVANCE(170);
      END_STATE();
    case 135:
      if (lookahead == '_') ADVANCE(171);
      END_STATE();
    case 136:
      if (lookahead == 'g') ADVANCE(172);
      if (lookahead == 's') ADVANCE(173);
      END_STATE();
    case 137:
      if (lookahead == 'h') ADVANCE(174);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 139:
      if (lookahead == 'e') ADVANCE(175);
      END_STATE();
    case 140:
      if (lookahead == 'a') ADVANCE(176);
      END_STATE();
    case 141:
      if (lookahead == 'l') ADVANCE(177);
      END_STATE();
    case 142:
      if (lookahead == 't') ADVANCE(178);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_push);
      END_STATE();
    case 144:
      if (lookahead == 'e') ADVANCE(179);
      END_STATE();
    case 145:
      if (lookahead == '_') ADVANCE(180);
      END_STATE();
    case 146:
      if (lookahead == 'r') ADVANCE(181);
      END_STATE();
    case 147:
      if (lookahead == 'r') ADVANCE(182);
      END_STATE();
    case 148:
      if (lookahead == 'c') ADVANCE(183);
      END_STATE();
    case 149:
      if (lookahead == 'n') ADVANCE(184);
      END_STATE();
    case 150:
      if (lookahead == 't') ADVANCE(185);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_sqrt);
      END_STATE();
    case 152:
      if (lookahead == 'n') ADVANCE(186);
      END_STATE();
    case 153:
      if (lookahead == 'c') ADVANCE(187);
      END_STATE();
    case 154:
      if (lookahead == 't') ADVANCE(188);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 158:
      if (lookahead == 'e') ADVANCE(189);
      END_STATE();
    case 159:
      if (lookahead == 'e') ADVANCE(190);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 161:
      if (lookahead == 'n') ADVANCE(191);
      END_STATE();
    case 162:
      if (lookahead == 'n') ADVANCE(192);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_floor);
      END_STATE();
    case 166:
      if (lookahead == 'v') ADVANCE(193);
      END_STATE();
    case 167:
      if (lookahead == 't') ADVANCE(194);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_inout);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 170:
      if (lookahead == 'l') ADVANCE(195);
      END_STATE();
    case 171:
      if (lookahead == 'd') ADVANCE(196);
      END_STATE();
    case 172:
      if (lookahead == 'e') ADVANCE(197);
      END_STATE();
    case 173:
      if (lookahead == 'e') ADVANCE(198);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 175:
      if (lookahead == 't') ADVANCE(199);
      END_STATE();
    case 176:
      if (lookahead == 'g') ADVANCE(200);
      END_STATE();
    case 177:
      if (lookahead == 'l') ADVANCE(201);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_print);
      if (lookahead == 'l') ADVANCE(202);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_range);
      END_STATE();
    case 180:
      if (lookahead == 'a') ADVANCE(203);
      if (lookahead == 'f') ADVANCE(204);
      END_STATE();
    case 181:
      if (lookahead == 'v') ADVANCE(205);
      END_STATE();
    case 182:
      if (lookahead == 'n') ADVANCE(206);
      END_STATE();
    case 183:
      if (lookahead == 't') ADVANCE(207);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_spawn);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(anon_sym_split);
      END_STATE();
    case 186:
      if (lookahead == 'g') ADVANCE(208);
      END_STATE();
    case 187:
      if (lookahead == 't') ADVANCE(209);
      END_STATE();
    case 188:
      if (lookahead == 'r') ADVANCE(210);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 190:
      if (lookahead == '_') ADVANCE(211);
      END_STATE();
    case 191:
      if (lookahead == 'u') ADVANCE(212);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(anon_sym_getenv);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 195:
      if (lookahead == 'l') ADVANCE(213);
      END_STATE();
    case 196:
      if (lookahead == 'i') ADVANCE(214);
      END_STATE();
    case 197:
      if (lookahead == 't') ADVANCE(215);
      END_STATE();
    case 198:
      if (lookahead == 't') ADVANCE(216);
      END_STATE();
    case 199:
      if (lookahead == 'u') ADVANCE(217);
      END_STATE();
    case 200:
      if (lookahead == 'e') ADVANCE(218);
      END_STATE();
    case 201:
      if (lookahead == 'e') ADVANCE(219);
      END_STATE();
    case 202:
      if (lookahead == 'n') ADVANCE(220);
      END_STATE();
    case 203:
      if (lookahead == 'l') ADVANCE(221);
      END_STATE();
    case 204:
      if (lookahead == 'i') ADVANCE(222);
      END_STATE();
    case 205:
      if (lookahead == 'e') ADVANCE(223);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(anon_sym_select);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(anon_sym_substr);
      END_STATE();
    case 211:
      if (lookahead == 'f') ADVANCE(224);
      END_STATE();
    case 212:
      if (lookahead == 'e') ADVANCE(225);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(anon_sym_is_null);
      END_STATE();
    case 214:
      if (lookahead == 'r') ADVANCE(226);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(anon_sym_map_get);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(anon_sym_map_set);
      END_STATE();
    case 217:
      if (lookahead == 'r') ADVANCE(227);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 219:
      if (lookahead == 'l') ADVANCE(228);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(anon_sym_println);
      END_STATE();
    case 221:
      if (lookahead == 'l') ADVANCE(229);
      END_STATE();
    case 222:
      if (lookahead == 'l') ADVANCE(230);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(anon_sym_reserve);
      END_STATE();
    case 224:
      if (lookahead == 'i') ADVANCE(231);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(anon_sym_list_dir);
      END_STATE();
    case 227:
      if (lookahead == 'n') ADVANCE(232);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(anon_sym_parallel);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(anon_sym_read_all);
      END_STATE();
    case 230:
      if (lookahead == 'e') ADVANCE(233);
      END_STATE();
    case 231:
      if (lookahead == 'l') ADVANCE(234);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(anon_sym_or_return);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(anon_sym_read_file);
      END_STATE();
    case 234:
      if (lookahead == 'e') ADVANCE(235);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(anon_sym_write_file);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_select] = ACTIONS(1),
    [anon_sym_parallel] = ACTIONS(1),
    [anon_sym_spawn] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_or_return] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_inout] = ACTIONS(1),
    [anon_sym_soa] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_ptr] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_println] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_len] = ACTIONS(1),
    [anon_sym_push] = ACTIONS(1),
    [anon_sym_pop] = ACTIONS(1),
    [anon_sym_range] = ACTIONS(1),
    [anon_sym_split] = ACTIONS(1),
    [anon_sym_substr] = ACTIONS(1),
    [anon_sym_find] = ACTIONS(1),
    [anon_sym_read_file] = ACTIONS(1),
    [anon_sym_write_file] = ACTIONS(1),
    [anon_sym_read_all] = ACTIONS(1),
    [anon_sym_list_dir] = ACTIONS(1),
    [anon_sym_args] = ACTIONS(1),
    [anon_sym_getenv] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_chr] = ACTIONS(1),
    [anon_sym_die] = ACTIONS(1),
    [anon_sym_is_null] = ACTIONS(1),
    [anon_sym_sqrt] = ACTIONS(1),
    [anon_sym_pow] = ACTIONS(1),
    [anon_sym_floor] = ACTIONS(1),
    [anon_sym_fabs] = ACTIONS(1),
    [anon_sym_map_get] = ACTIONS(1),
    [anon_sym_map_set] = ACTIONS(1),
    [anon_sym_reserve] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_fstring] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_AMP_EQ] = ACTIONS(1),
    [anon_sym_PIPE_EQ] = ACTIONS(1),
    [anon_sym_CARET_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym__token] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_constant] = STATE(2),
    [sym_type] = STATE(2),
    [sym_builtin] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_punctuation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_elif] = ACTIONS(9),
    [anon_sym_else] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(9),
    [anon_sym_match] = ACTIONS(9),
    [anon_sym_select] = ACTIONS(9),
    [anon_sym_parallel] = ACTIONS(9),
    [anon_sym_spawn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_break] = ACTIONS(9),
    [anon_sym_continue] = ACTIONS(9),
    [anon_sym_or_return] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_enum] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_package] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(9),
    [anon_sym_inout] = ACTIONS(9),
    [anon_sym_soa] = ACTIONS(9),
    [anon_sym_and] = ACTIONS(9),
    [anon_sym_or] = ACTIONS(9),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_null] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(13),
    [anon_sym_float] = ACTIONS(13),
    [anon_sym_string] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [anon_sym_char] = ACTIONS(13),
    [anon_sym_ptr] = ACTIONS(13),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_println] = ACTIONS(15),
    [anon_sym_str] = ACTIONS(15),
    [anon_sym_len] = ACTIONS(15),
    [anon_sym_push] = ACTIONS(15),
    [anon_sym_pop] = ACTIONS(15),
    [anon_sym_range] = ACTIONS(15),
    [anon_sym_split] = ACTIONS(15),
    [anon_sym_substr] = ACTIONS(15),
    [anon_sym_find] = ACTIONS(15),
    [anon_sym_read_file] = ACTIONS(15),
    [anon_sym_write_file] = ACTIONS(15),
    [anon_sym_read_all] = ACTIONS(15),
    [anon_sym_list_dir] = ACTIONS(15),
    [anon_sym_args] = ACTIONS(15),
    [anon_sym_getenv] = ACTIONS(15),
    [anon_sym_input] = ACTIONS(15),
    [anon_sym_chr] = ACTIONS(15),
    [anon_sym_die] = ACTIONS(15),
    [anon_sym_is_null] = ACTIONS(15),
    [anon_sym_sqrt] = ACTIONS(15),
    [anon_sym_pow] = ACTIONS(15),
    [anon_sym_floor] = ACTIONS(15),
    [anon_sym_fabs] = ACTIONS(15),
    [anon_sym_map_get] = ACTIONS(15),
    [anon_sym_map_set] = ACTIONS(15),
    [anon_sym_reserve] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [sym_fstring] = ACTIONS(17),
    [sym_char] = ACTIONS(17),
    [anon_sym_COLON_EQ] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS_EQ] = ACTIONS(19),
    [anon_sym_DASH_EQ] = ACTIONS(19),
    [anon_sym_STAR_EQ] = ACTIONS(19),
    [anon_sym_SLASH_EQ] = ACTIONS(19),
    [anon_sym_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_AMP_EQ] = ACTIONS(19),
    [anon_sym_PIPE_EQ] = ACTIONS(19),
    [anon_sym_CARET_EQ] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_TILDE] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__token] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_type] = STATE(3),
    [sym_builtin] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_elif] = ACTIONS(9),
    [anon_sym_else] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(9),
    [anon_sym_match] = ACTIONS(9),
    [anon_sym_select] = ACTIONS(9),
    [anon_sym_parallel] = ACTIONS(9),
    [anon_sym_spawn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_break] = ACTIONS(9),
    [anon_sym_continue] = ACTIONS(9),
    [anon_sym_or_return] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_enum] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(9),
    [anon_sym_package] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(9),
    [anon_sym_inout] = ACTIONS(9),
    [anon_sym_soa] = ACTIONS(9),
    [anon_sym_and] = ACTIONS(9),
    [anon_sym_or] = ACTIONS(9),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_null] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(13),
    [anon_sym_float] = ACTIONS(13),
    [anon_sym_string] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [anon_sym_char] = ACTIONS(13),
    [anon_sym_ptr] = ACTIONS(13),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_println] = ACTIONS(15),
    [anon_sym_str] = ACTIONS(15),
    [anon_sym_len] = ACTIONS(15),
    [anon_sym_push] = ACTIONS(15),
    [anon_sym_pop] = ACTIONS(15),
    [anon_sym_range] = ACTIONS(15),
    [anon_sym_split] = ACTIONS(15),
    [anon_sym_substr] = ACTIONS(15),
    [anon_sym_find] = ACTIONS(15),
    [anon_sym_read_file] = ACTIONS(15),
    [anon_sym_write_file] = ACTIONS(15),
    [anon_sym_read_all] = ACTIONS(15),
    [anon_sym_list_dir] = ACTIONS(15),
    [anon_sym_args] = ACTIONS(15),
    [anon_sym_getenv] = ACTIONS(15),
    [anon_sym_input] = ACTIONS(15),
    [anon_sym_chr] = ACTIONS(15),
    [anon_sym_die] = ACTIONS(15),
    [anon_sym_is_null] = ACTIONS(15),
    [anon_sym_sqrt] = ACTIONS(15),
    [anon_sym_pow] = ACTIONS(15),
    [anon_sym_floor] = ACTIONS(15),
    [anon_sym_fabs] = ACTIONS(15),
    [anon_sym_map_get] = ACTIONS(15),
    [anon_sym_map_set] = ACTIONS(15),
    [anon_sym_reserve] = ACTIONS(15),
    [sym_number] = ACTIONS(31),
    [sym_string] = ACTIONS(31),
    [sym_fstring] = ACTIONS(31),
    [sym_char] = ACTIONS(31),
    [anon_sym_COLON_EQ] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS_EQ] = ACTIONS(19),
    [anon_sym_DASH_EQ] = ACTIONS(19),
    [anon_sym_STAR_EQ] = ACTIONS(19),
    [anon_sym_SLASH_EQ] = ACTIONS(19),
    [anon_sym_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_AMP_EQ] = ACTIONS(19),
    [anon_sym_PIPE_EQ] = ACTIONS(19),
    [anon_sym_CARET_EQ] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_TILDE] = ACTIONS(19),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym__token] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_constant] = STATE(3),
    [sym_type] = STATE(3),
    [sym_builtin] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(38),
    [anon_sym_if] = ACTIONS(38),
    [anon_sym_elif] = ACTIONS(38),
    [anon_sym_else] = ACTIONS(38),
    [anon_sym_for] = ACTIONS(38),
    [anon_sym_while] = ACTIONS(38),
    [anon_sym_in] = ACTIONS(38),
    [anon_sym_match] = ACTIONS(38),
    [anon_sym_select] = ACTIONS(38),
    [anon_sym_parallel] = ACTIONS(38),
    [anon_sym_spawn] = ACTIONS(38),
    [anon_sym_return] = ACTIONS(38),
    [anon_sym_break] = ACTIONS(38),
    [anon_sym_continue] = ACTIONS(38),
    [anon_sym_or_return] = ACTIONS(38),
    [anon_sym_struct] = ACTIONS(38),
    [anon_sym_enum] = ACTIONS(38),
    [anon_sym_type] = ACTIONS(38),
    [anon_sym_import] = ACTIONS(38),
    [anon_sym_package] = ACTIONS(38),
    [anon_sym_extern] = ACTIONS(38),
    [anon_sym_inout] = ACTIONS(38),
    [anon_sym_soa] = ACTIONS(38),
    [anon_sym_and] = ACTIONS(38),
    [anon_sym_or] = ACTIONS(38),
    [anon_sym_not] = ACTIONS(38),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [anon_sym_null] = ACTIONS(41),
    [anon_sym_int] = ACTIONS(44),
    [anon_sym_float] = ACTIONS(44),
    [anon_sym_string] = ACTIONS(44),
    [anon_sym_bool] = ACTIONS(44),
    [anon_sym_char] = ACTIONS(44),
    [anon_sym_ptr] = ACTIONS(44),
    [anon_sym_void] = ACTIONS(44),
    [anon_sym_print] = ACTIONS(47),
    [anon_sym_println] = ACTIONS(47),
    [anon_sym_str] = ACTIONS(47),
    [anon_sym_len] = ACTIONS(47),
    [anon_sym_push] = ACTIONS(47),
    [anon_sym_pop] = ACTIONS(47),
    [anon_sym_range] = ACTIONS(47),
    [anon_sym_split] = ACTIONS(47),
    [anon_sym_substr] = ACTIONS(47),
    [anon_sym_find] = ACTIONS(47),
    [anon_sym_read_file] = ACTIONS(47),
    [anon_sym_write_file] = ACTIONS(47),
    [anon_sym_read_all] = ACTIONS(47),
    [anon_sym_list_dir] = ACTIONS(47),
    [anon_sym_args] = ACTIONS(47),
    [anon_sym_getenv] = ACTIONS(47),
    [anon_sym_input] = ACTIONS(47),
    [anon_sym_chr] = ACTIONS(47),
    [anon_sym_die] = ACTIONS(47),
    [anon_sym_is_null] = ACTIONS(47),
    [anon_sym_sqrt] = ACTIONS(47),
    [anon_sym_pow] = ACTIONS(47),
    [anon_sym_floor] = ACTIONS(47),
    [anon_sym_fabs] = ACTIONS(47),
    [anon_sym_map_get] = ACTIONS(47),
    [anon_sym_map_set] = ACTIONS(47),
    [anon_sym_reserve] = ACTIONS(47),
    [sym_number] = ACTIONS(50),
    [sym_string] = ACTIONS(50),
    [sym_fstring] = ACTIONS(50),
    [sym_char] = ACTIONS(50),
    [anon_sym_COLON_EQ] = ACTIONS(53),
    [anon_sym_DASH_GT] = ACTIONS(53),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_BANG_EQ] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_LT_LT] = ACTIONS(53),
    [anon_sym_GT_GT] = ACTIONS(53),
    [anon_sym_PLUS_EQ] = ACTIONS(53),
    [anon_sym_DASH_EQ] = ACTIONS(53),
    [anon_sym_STAR_EQ] = ACTIONS(53),
    [anon_sym_SLASH_EQ] = ACTIONS(53),
    [anon_sym_PERCENT_EQ] = ACTIONS(53),
    [anon_sym_AMP_EQ] = ACTIONS(53),
    [anon_sym_PIPE_EQ] = ACTIONS(53),
    [anon_sym_CARET_EQ] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(56),
    [anon_sym_DASH] = ACTIONS(56),
    [anon_sym_STAR] = ACTIONS(56),
    [anon_sym_SLASH] = ACTIONS(56),
    [anon_sym_PERCENT] = ACTIONS(56),
    [anon_sym_LT] = ACTIONS(56),
    [anon_sym_GT] = ACTIONS(56),
    [anon_sym_EQ] = ACTIONS(56),
    [anon_sym_AMP] = ACTIONS(56),
    [anon_sym_PIPE] = ACTIONS(56),
    [anon_sym_CARET] = ACTIONS(56),
    [anon_sym_TILDE] = ACTIONS(53),
    [anon_sym_DOT] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(59),
    [anon_sym_RBRACK] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(62),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(67),
    [anon_sym_if] = ACTIONS(67),
    [anon_sym_elif] = ACTIONS(67),
    [anon_sym_else] = ACTIONS(67),
    [anon_sym_for] = ACTIONS(67),
    [anon_sym_while] = ACTIONS(67),
    [anon_sym_in] = ACTIONS(67),
    [anon_sym_match] = ACTIONS(67),
    [anon_sym_select] = ACTIONS(67),
    [anon_sym_parallel] = ACTIONS(67),
    [anon_sym_spawn] = ACTIONS(67),
    [anon_sym_return] = ACTIONS(67),
    [anon_sym_break] = ACTIONS(67),
    [anon_sym_continue] = ACTIONS(67),
    [anon_sym_or_return] = ACTIONS(67),
    [anon_sym_struct] = ACTIONS(67),
    [anon_sym_enum] = ACTIONS(67),
    [anon_sym_type] = ACTIONS(67),
    [anon_sym_import] = ACTIONS(67),
    [anon_sym_package] = ACTIONS(67),
    [anon_sym_extern] = ACTIONS(67),
    [anon_sym_inout] = ACTIONS(67),
    [anon_sym_soa] = ACTIONS(67),
    [anon_sym_and] = ACTIONS(67),
    [anon_sym_or] = ACTIONS(67),
    [anon_sym_not] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [anon_sym_null] = ACTIONS(67),
    [anon_sym_int] = ACTIONS(67),
    [anon_sym_float] = ACTIONS(67),
    [anon_sym_string] = ACTIONS(67),
    [anon_sym_bool] = ACTIONS(67),
    [anon_sym_char] = ACTIONS(67),
    [anon_sym_ptr] = ACTIONS(67),
    [anon_sym_void] = ACTIONS(67),
    [anon_sym_print] = ACTIONS(67),
    [anon_sym_println] = ACTIONS(67),
    [anon_sym_str] = ACTIONS(67),
    [anon_sym_len] = ACTIONS(67),
    [anon_sym_push] = ACTIONS(67),
    [anon_sym_pop] = ACTIONS(67),
    [anon_sym_range] = ACTIONS(67),
    [anon_sym_split] = ACTIONS(67),
    [anon_sym_substr] = ACTIONS(67),
    [anon_sym_find] = ACTIONS(67),
    [anon_sym_read_file] = ACTIONS(67),
    [anon_sym_write_file] = ACTIONS(67),
    [anon_sym_read_all] = ACTIONS(67),
    [anon_sym_list_dir] = ACTIONS(67),
    [anon_sym_args] = ACTIONS(67),
    [anon_sym_getenv] = ACTIONS(67),
    [anon_sym_input] = ACTIONS(67),
    [anon_sym_chr] = ACTIONS(67),
    [anon_sym_die] = ACTIONS(67),
    [anon_sym_is_null] = ACTIONS(67),
    [anon_sym_sqrt] = ACTIONS(67),
    [anon_sym_pow] = ACTIONS(67),
    [anon_sym_floor] = ACTIONS(67),
    [anon_sym_fabs] = ACTIONS(67),
    [anon_sym_map_get] = ACTIONS(67),
    [anon_sym_map_set] = ACTIONS(67),
    [anon_sym_reserve] = ACTIONS(67),
    [sym_number] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [sym_fstring] = ACTIONS(65),
    [sym_char] = ACTIONS(65),
    [anon_sym_COLON_EQ] = ACTIONS(65),
    [anon_sym_DASH_GT] = ACTIONS(65),
    [anon_sym_EQ_EQ] = ACTIONS(65),
    [anon_sym_BANG_EQ] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(65),
    [anon_sym_GT_EQ] = ACTIONS(65),
    [anon_sym_LT_LT] = ACTIONS(65),
    [anon_sym_GT_GT] = ACTIONS(65),
    [anon_sym_PLUS_EQ] = ACTIONS(65),
    [anon_sym_DASH_EQ] = ACTIONS(65),
    [anon_sym_STAR_EQ] = ACTIONS(65),
    [anon_sym_SLASH_EQ] = ACTIONS(65),
    [anon_sym_PERCENT_EQ] = ACTIONS(65),
    [anon_sym_AMP_EQ] = ACTIONS(65),
    [anon_sym_PIPE_EQ] = ACTIONS(65),
    [anon_sym_CARET_EQ] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(67),
    [anon_sym_DASH] = ACTIONS(67),
    [anon_sym_STAR] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_PERCENT] = ACTIONS(67),
    [anon_sym_LT] = ACTIONS(67),
    [anon_sym_GT] = ACTIONS(67),
    [anon_sym_EQ] = ACTIONS(67),
    [anon_sym_AMP] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_CARET] = ACTIONS(67),
    [anon_sym_TILDE] = ACTIONS(65),
    [anon_sym_DOT] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(65),
    [anon_sym_RBRACK] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(65),
    [anon_sym_COMMA] = ACTIONS(65),
    [anon_sym_COLON] = ACTIONS(67),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(71),
    [anon_sym_if] = ACTIONS(71),
    [anon_sym_elif] = ACTIONS(71),
    [anon_sym_else] = ACTIONS(71),
    [anon_sym_for] = ACTIONS(71),
    [anon_sym_while] = ACTIONS(71),
    [anon_sym_in] = ACTIONS(71),
    [anon_sym_match] = ACTIONS(71),
    [anon_sym_select] = ACTIONS(71),
    [anon_sym_parallel] = ACTIONS(71),
    [anon_sym_spawn] = ACTIONS(71),
    [anon_sym_return] = ACTIONS(71),
    [anon_sym_break] = ACTIONS(71),
    [anon_sym_continue] = ACTIONS(71),
    [anon_sym_or_return] = ACTIONS(71),
    [anon_sym_struct] = ACTIONS(71),
    [anon_sym_enum] = ACTIONS(71),
    [anon_sym_type] = ACTIONS(71),
    [anon_sym_import] = ACTIONS(71),
    [anon_sym_package] = ACTIONS(71),
    [anon_sym_extern] = ACTIONS(71),
    [anon_sym_inout] = ACTIONS(71),
    [anon_sym_soa] = ACTIONS(71),
    [anon_sym_and] = ACTIONS(71),
    [anon_sym_or] = ACTIONS(71),
    [anon_sym_not] = ACTIONS(71),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [anon_sym_null] = ACTIONS(71),
    [anon_sym_int] = ACTIONS(71),
    [anon_sym_float] = ACTIONS(71),
    [anon_sym_string] = ACTIONS(71),
    [anon_sym_bool] = ACTIONS(71),
    [anon_sym_char] = ACTIONS(71),
    [anon_sym_ptr] = ACTIONS(71),
    [anon_sym_void] = ACTIONS(71),
    [anon_sym_print] = ACTIONS(71),
    [anon_sym_println] = ACTIONS(71),
    [anon_sym_str] = ACTIONS(71),
    [anon_sym_len] = ACTIONS(71),
    [anon_sym_push] = ACTIONS(71),
    [anon_sym_pop] = ACTIONS(71),
    [anon_sym_range] = ACTIONS(71),
    [anon_sym_split] = ACTIONS(71),
    [anon_sym_substr] = ACTIONS(71),
    [anon_sym_find] = ACTIONS(71),
    [anon_sym_read_file] = ACTIONS(71),
    [anon_sym_write_file] = ACTIONS(71),
    [anon_sym_read_all] = ACTIONS(71),
    [anon_sym_list_dir] = ACTIONS(71),
    [anon_sym_args] = ACTIONS(71),
    [anon_sym_getenv] = ACTIONS(71),
    [anon_sym_input] = ACTIONS(71),
    [anon_sym_chr] = ACTIONS(71),
    [anon_sym_die] = ACTIONS(71),
    [anon_sym_is_null] = ACTIONS(71),
    [anon_sym_sqrt] = ACTIONS(71),
    [anon_sym_pow] = ACTIONS(71),
    [anon_sym_floor] = ACTIONS(71),
    [anon_sym_fabs] = ACTIONS(71),
    [anon_sym_map_get] = ACTIONS(71),
    [anon_sym_map_set] = ACTIONS(71),
    [anon_sym_reserve] = ACTIONS(71),
    [sym_number] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
    [sym_fstring] = ACTIONS(69),
    [sym_char] = ACTIONS(69),
    [anon_sym_COLON_EQ] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(69),
    [anon_sym_BANG_EQ] = ACTIONS(69),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_LT_LT] = ACTIONS(69),
    [anon_sym_GT_GT] = ACTIONS(69),
    [anon_sym_PLUS_EQ] = ACTIONS(69),
    [anon_sym_DASH_EQ] = ACTIONS(69),
    [anon_sym_STAR_EQ] = ACTIONS(69),
    [anon_sym_SLASH_EQ] = ACTIONS(69),
    [anon_sym_PERCENT_EQ] = ACTIONS(69),
    [anon_sym_AMP_EQ] = ACTIONS(69),
    [anon_sym_PIPE_EQ] = ACTIONS(69),
    [anon_sym_CARET_EQ] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(71),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_STAR] = ACTIONS(71),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_PERCENT] = ACTIONS(71),
    [anon_sym_LT] = ACTIONS(71),
    [anon_sym_GT] = ACTIONS(71),
    [anon_sym_EQ] = ACTIONS(71),
    [anon_sym_AMP] = ACTIONS(71),
    [anon_sym_PIPE] = ACTIONS(71),
    [anon_sym_CARET] = ACTIONS(71),
    [anon_sym_TILDE] = ACTIONS(69),
    [anon_sym_DOT] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(69),
    [anon_sym_RBRACK] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_COLON] = ACTIONS(71),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(75),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(75),
    [anon_sym_if] = ACTIONS(75),
    [anon_sym_elif] = ACTIONS(75),
    [anon_sym_else] = ACTIONS(75),
    [anon_sym_for] = ACTIONS(75),
    [anon_sym_while] = ACTIONS(75),
    [anon_sym_in] = ACTIONS(75),
    [anon_sym_match] = ACTIONS(75),
    [anon_sym_select] = ACTIONS(75),
    [anon_sym_parallel] = ACTIONS(75),
    [anon_sym_spawn] = ACTIONS(75),
    [anon_sym_return] = ACTIONS(75),
    [anon_sym_break] = ACTIONS(75),
    [anon_sym_continue] = ACTIONS(75),
    [anon_sym_or_return] = ACTIONS(75),
    [anon_sym_struct] = ACTIONS(75),
    [anon_sym_enum] = ACTIONS(75),
    [anon_sym_type] = ACTIONS(75),
    [anon_sym_import] = ACTIONS(75),
    [anon_sym_package] = ACTIONS(75),
    [anon_sym_extern] = ACTIONS(75),
    [anon_sym_inout] = ACTIONS(75),
    [anon_sym_soa] = ACTIONS(75),
    [anon_sym_and] = ACTIONS(75),
    [anon_sym_or] = ACTIONS(75),
    [anon_sym_not] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [anon_sym_null] = ACTIONS(75),
    [anon_sym_int] = ACTIONS(75),
    [anon_sym_float] = ACTIONS(75),
    [anon_sym_string] = ACTIONS(75),
    [anon_sym_bool] = ACTIONS(75),
    [anon_sym_char] = ACTIONS(75),
    [anon_sym_ptr] = ACTIONS(75),
    [anon_sym_void] = ACTIONS(75),
    [anon_sym_print] = ACTIONS(75),
    [anon_sym_println] = ACTIONS(75),
    [anon_sym_str] = ACTIONS(75),
    [anon_sym_len] = ACTIONS(75),
    [anon_sym_push] = ACTIONS(75),
    [anon_sym_pop] = ACTIONS(75),
    [anon_sym_range] = ACTIONS(75),
    [anon_sym_split] = ACTIONS(75),
    [anon_sym_substr] = ACTIONS(75),
    [anon_sym_find] = ACTIONS(75),
    [anon_sym_read_file] = ACTIONS(75),
    [anon_sym_write_file] = ACTIONS(75),
    [anon_sym_read_all] = ACTIONS(75),
    [anon_sym_list_dir] = ACTIONS(75),
    [anon_sym_args] = ACTIONS(75),
    [anon_sym_getenv] = ACTIONS(75),
    [anon_sym_input] = ACTIONS(75),
    [anon_sym_chr] = ACTIONS(75),
    [anon_sym_die] = ACTIONS(75),
    [anon_sym_is_null] = ACTIONS(75),
    [anon_sym_sqrt] = ACTIONS(75),
    [anon_sym_pow] = ACTIONS(75),
    [anon_sym_floor] = ACTIONS(75),
    [anon_sym_fabs] = ACTIONS(75),
    [anon_sym_map_get] = ACTIONS(75),
    [anon_sym_map_set] = ACTIONS(75),
    [anon_sym_reserve] = ACTIONS(75),
    [sym_number] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
    [sym_fstring] = ACTIONS(73),
    [sym_char] = ACTIONS(73),
    [anon_sym_COLON_EQ] = ACTIONS(73),
    [anon_sym_DASH_GT] = ACTIONS(73),
    [anon_sym_EQ_EQ] = ACTIONS(73),
    [anon_sym_BANG_EQ] = ACTIONS(73),
    [anon_sym_LT_EQ] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(73),
    [anon_sym_LT_LT] = ACTIONS(73),
    [anon_sym_GT_GT] = ACTIONS(73),
    [anon_sym_PLUS_EQ] = ACTIONS(73),
    [anon_sym_DASH_EQ] = ACTIONS(73),
    [anon_sym_STAR_EQ] = ACTIONS(73),
    [anon_sym_SLASH_EQ] = ACTIONS(73),
    [anon_sym_PERCENT_EQ] = ACTIONS(73),
    [anon_sym_AMP_EQ] = ACTIONS(73),
    [anon_sym_PIPE_EQ] = ACTIONS(73),
    [anon_sym_CARET_EQ] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(75),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_PERCENT] = ACTIONS(75),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(75),
    [anon_sym_AMP] = ACTIONS(75),
    [anon_sym_PIPE] = ACTIONS(75),
    [anon_sym_CARET] = ACTIONS(75),
    [anon_sym_TILDE] = ACTIONS(73),
    [anon_sym_DOT] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(73),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(73),
    [anon_sym_COLON] = ACTIONS(75),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_identifier] = ACTIONS(79),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(79),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_elif] = ACTIONS(79),
    [anon_sym_else] = ACTIONS(79),
    [anon_sym_for] = ACTIONS(79),
    [anon_sym_while] = ACTIONS(79),
    [anon_sym_in] = ACTIONS(79),
    [anon_sym_match] = ACTIONS(79),
    [anon_sym_select] = ACTIONS(79),
    [anon_sym_parallel] = ACTIONS(79),
    [anon_sym_spawn] = ACTIONS(79),
    [anon_sym_return] = ACTIONS(79),
    [anon_sym_break] = ACTIONS(79),
    [anon_sym_continue] = ACTIONS(79),
    [anon_sym_or_return] = ACTIONS(79),
    [anon_sym_struct] = ACTIONS(79),
    [anon_sym_enum] = ACTIONS(79),
    [anon_sym_type] = ACTIONS(79),
    [anon_sym_import] = ACTIONS(79),
    [anon_sym_package] = ACTIONS(79),
    [anon_sym_extern] = ACTIONS(79),
    [anon_sym_inout] = ACTIONS(79),
    [anon_sym_soa] = ACTIONS(79),
    [anon_sym_and] = ACTIONS(79),
    [anon_sym_or] = ACTIONS(79),
    [anon_sym_not] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(79),
    [anon_sym_false] = ACTIONS(79),
    [anon_sym_null] = ACTIONS(79),
    [anon_sym_int] = ACTIONS(79),
    [anon_sym_float] = ACTIONS(79),
    [anon_sym_string] = ACTIONS(79),
    [anon_sym_bool] = ACTIONS(79),
    [anon_sym_char] = ACTIONS(79),
    [anon_sym_ptr] = ACTIONS(79),
    [anon_sym_void] = ACTIONS(79),
    [anon_sym_print] = ACTIONS(79),
    [anon_sym_println] = ACTIONS(79),
    [anon_sym_str] = ACTIONS(79),
    [anon_sym_len] = ACTIONS(79),
    [anon_sym_push] = ACTIONS(79),
    [anon_sym_pop] = ACTIONS(79),
    [anon_sym_range] = ACTIONS(79),
    [anon_sym_split] = ACTIONS(79),
    [anon_sym_substr] = ACTIONS(79),
    [anon_sym_find] = ACTIONS(79),
    [anon_sym_read_file] = ACTIONS(79),
    [anon_sym_write_file] = ACTIONS(79),
    [anon_sym_read_all] = ACTIONS(79),
    [anon_sym_list_dir] = ACTIONS(79),
    [anon_sym_args] = ACTIONS(79),
    [anon_sym_getenv] = ACTIONS(79),
    [anon_sym_input] = ACTIONS(79),
    [anon_sym_chr] = ACTIONS(79),
    [anon_sym_die] = ACTIONS(79),
    [anon_sym_is_null] = ACTIONS(79),
    [anon_sym_sqrt] = ACTIONS(79),
    [anon_sym_pow] = ACTIONS(79),
    [anon_sym_floor] = ACTIONS(79),
    [anon_sym_fabs] = ACTIONS(79),
    [anon_sym_map_get] = ACTIONS(79),
    [anon_sym_map_set] = ACTIONS(79),
    [anon_sym_reserve] = ACTIONS(79),
    [sym_number] = ACTIONS(77),
    [sym_string] = ACTIONS(77),
    [sym_fstring] = ACTIONS(77),
    [sym_char] = ACTIONS(77),
    [anon_sym_COLON_EQ] = ACTIONS(77),
    [anon_sym_DASH_GT] = ACTIONS(77),
    [anon_sym_EQ_EQ] = ACTIONS(77),
    [anon_sym_BANG_EQ] = ACTIONS(77),
    [anon_sym_LT_EQ] = ACTIONS(77),
    [anon_sym_GT_EQ] = ACTIONS(77),
    [anon_sym_LT_LT] = ACTIONS(77),
    [anon_sym_GT_GT] = ACTIONS(77),
    [anon_sym_PLUS_EQ] = ACTIONS(77),
    [anon_sym_DASH_EQ] = ACTIONS(77),
    [anon_sym_STAR_EQ] = ACTIONS(77),
    [anon_sym_SLASH_EQ] = ACTIONS(77),
    [anon_sym_PERCENT_EQ] = ACTIONS(77),
    [anon_sym_AMP_EQ] = ACTIONS(77),
    [anon_sym_PIPE_EQ] = ACTIONS(77),
    [anon_sym_CARET_EQ] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(79),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_PERCENT] = ACTIONS(79),
    [anon_sym_LT] = ACTIONS(79),
    [anon_sym_GT] = ACTIONS(79),
    [anon_sym_EQ] = ACTIONS(79),
    [anon_sym_AMP] = ACTIONS(79),
    [anon_sym_PIPE] = ACTIONS(79),
    [anon_sym_CARET] = ACTIONS(79),
    [anon_sym_TILDE] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_COLON] = ACTIONS(79),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_elif] = ACTIONS(83),
    [anon_sym_else] = ACTIONS(83),
    [anon_sym_for] = ACTIONS(83),
    [anon_sym_while] = ACTIONS(83),
    [anon_sym_in] = ACTIONS(83),
    [anon_sym_match] = ACTIONS(83),
    [anon_sym_select] = ACTIONS(83),
    [anon_sym_parallel] = ACTIONS(83),
    [anon_sym_spawn] = ACTIONS(83),
    [anon_sym_return] = ACTIONS(83),
    [anon_sym_break] = ACTIONS(83),
    [anon_sym_continue] = ACTIONS(83),
    [anon_sym_or_return] = ACTIONS(83),
    [anon_sym_struct] = ACTIONS(83),
    [anon_sym_enum] = ACTIONS(83),
    [anon_sym_type] = ACTIONS(83),
    [anon_sym_import] = ACTIONS(83),
    [anon_sym_package] = ACTIONS(83),
    [anon_sym_extern] = ACTIONS(83),
    [anon_sym_inout] = ACTIONS(83),
    [anon_sym_soa] = ACTIONS(83),
    [anon_sym_and] = ACTIONS(83),
    [anon_sym_or] = ACTIONS(83),
    [anon_sym_not] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(83),
    [anon_sym_false] = ACTIONS(83),
    [anon_sym_null] = ACTIONS(83),
    [anon_sym_int] = ACTIONS(83),
    [anon_sym_float] = ACTIONS(83),
    [anon_sym_string] = ACTIONS(83),
    [anon_sym_bool] = ACTIONS(83),
    [anon_sym_char] = ACTIONS(83),
    [anon_sym_ptr] = ACTIONS(83),
    [anon_sym_void] = ACTIONS(83),
    [anon_sym_print] = ACTIONS(83),
    [anon_sym_println] = ACTIONS(83),
    [anon_sym_str] = ACTIONS(83),
    [anon_sym_len] = ACTIONS(83),
    [anon_sym_push] = ACTIONS(83),
    [anon_sym_pop] = ACTIONS(83),
    [anon_sym_range] = ACTIONS(83),
    [anon_sym_split] = ACTIONS(83),
    [anon_sym_substr] = ACTIONS(83),
    [anon_sym_find] = ACTIONS(83),
    [anon_sym_read_file] = ACTIONS(83),
    [anon_sym_write_file] = ACTIONS(83),
    [anon_sym_read_all] = ACTIONS(83),
    [anon_sym_list_dir] = ACTIONS(83),
    [anon_sym_args] = ACTIONS(83),
    [anon_sym_getenv] = ACTIONS(83),
    [anon_sym_input] = ACTIONS(83),
    [anon_sym_chr] = ACTIONS(83),
    [anon_sym_die] = ACTIONS(83),
    [anon_sym_is_null] = ACTIONS(83),
    [anon_sym_sqrt] = ACTIONS(83),
    [anon_sym_pow] = ACTIONS(83),
    [anon_sym_floor] = ACTIONS(83),
    [anon_sym_fabs] = ACTIONS(83),
    [anon_sym_map_get] = ACTIONS(83),
    [anon_sym_map_set] = ACTIONS(83),
    [anon_sym_reserve] = ACTIONS(83),
    [sym_number] = ACTIONS(81),
    [sym_string] = ACTIONS(81),
    [sym_fstring] = ACTIONS(81),
    [sym_char] = ACTIONS(81),
    [anon_sym_COLON_EQ] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_PLUS_EQ] = ACTIONS(81),
    [anon_sym_DASH_EQ] = ACTIONS(81),
    [anon_sym_STAR_EQ] = ACTIONS(81),
    [anon_sym_SLASH_EQ] = ACTIONS(81),
    [anon_sym_PERCENT_EQ] = ACTIONS(81),
    [anon_sym_AMP_EQ] = ACTIONS(81),
    [anon_sym_PIPE_EQ] = ACTIONS(81),
    [anon_sym_CARET_EQ] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(83),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_PERCENT] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_AMP] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_CARET] = ACTIONS(83),
    [anon_sym_TILDE] = ACTIONS(81),
    [anon_sym_DOT] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_COLON] = ACTIONS(83),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_identifier] = ACTIONS(87),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(87),
    [anon_sym_if] = ACTIONS(87),
    [anon_sym_elif] = ACTIONS(87),
    [anon_sym_else] = ACTIONS(87),
    [anon_sym_for] = ACTIONS(87),
    [anon_sym_while] = ACTIONS(87),
    [anon_sym_in] = ACTIONS(87),
    [anon_sym_match] = ACTIONS(87),
    [anon_sym_select] = ACTIONS(87),
    [anon_sym_parallel] = ACTIONS(87),
    [anon_sym_spawn] = ACTIONS(87),
    [anon_sym_return] = ACTIONS(87),
    [anon_sym_break] = ACTIONS(87),
    [anon_sym_continue] = ACTIONS(87),
    [anon_sym_or_return] = ACTIONS(87),
    [anon_sym_struct] = ACTIONS(87),
    [anon_sym_enum] = ACTIONS(87),
    [anon_sym_type] = ACTIONS(87),
    [anon_sym_import] = ACTIONS(87),
    [anon_sym_package] = ACTIONS(87),
    [anon_sym_extern] = ACTIONS(87),
    [anon_sym_inout] = ACTIONS(87),
    [anon_sym_soa] = ACTIONS(87),
    [anon_sym_and] = ACTIONS(87),
    [anon_sym_or] = ACTIONS(87),
    [anon_sym_not] = ACTIONS(87),
    [anon_sym_true] = ACTIONS(87),
    [anon_sym_false] = ACTIONS(87),
    [anon_sym_null] = ACTIONS(87),
    [anon_sym_int] = ACTIONS(87),
    [anon_sym_float] = ACTIONS(87),
    [anon_sym_string] = ACTIONS(87),
    [anon_sym_bool] = ACTIONS(87),
    [anon_sym_char] = ACTIONS(87),
    [anon_sym_ptr] = ACTIONS(87),
    [anon_sym_void] = ACTIONS(87),
    [anon_sym_print] = ACTIONS(87),
    [anon_sym_println] = ACTIONS(87),
    [anon_sym_str] = ACTIONS(87),
    [anon_sym_len] = ACTIONS(87),
    [anon_sym_push] = ACTIONS(87),
    [anon_sym_pop] = ACTIONS(87),
    [anon_sym_range] = ACTIONS(87),
    [anon_sym_split] = ACTIONS(87),
    [anon_sym_substr] = ACTIONS(87),
    [anon_sym_find] = ACTIONS(87),
    [anon_sym_read_file] = ACTIONS(87),
    [anon_sym_write_file] = ACTIONS(87),
    [anon_sym_read_all] = ACTIONS(87),
    [anon_sym_list_dir] = ACTIONS(87),
    [anon_sym_args] = ACTIONS(87),
    [anon_sym_getenv] = ACTIONS(87),
    [anon_sym_input] = ACTIONS(87),
    [anon_sym_chr] = ACTIONS(87),
    [anon_sym_die] = ACTIONS(87),
    [anon_sym_is_null] = ACTIONS(87),
    [anon_sym_sqrt] = ACTIONS(87),
    [anon_sym_pow] = ACTIONS(87),
    [anon_sym_floor] = ACTIONS(87),
    [anon_sym_fabs] = ACTIONS(87),
    [anon_sym_map_get] = ACTIONS(87),
    [anon_sym_map_set] = ACTIONS(87),
    [anon_sym_reserve] = ACTIONS(87),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [sym_fstring] = ACTIONS(85),
    [sym_char] = ACTIONS(85),
    [anon_sym_COLON_EQ] = ACTIONS(85),
    [anon_sym_DASH_GT] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(85),
    [anon_sym_BANG_EQ] = ACTIONS(85),
    [anon_sym_LT_EQ] = ACTIONS(85),
    [anon_sym_GT_EQ] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(85),
    [anon_sym_GT_GT] = ACTIONS(85),
    [anon_sym_PLUS_EQ] = ACTIONS(85),
    [anon_sym_DASH_EQ] = ACTIONS(85),
    [anon_sym_STAR_EQ] = ACTIONS(85),
    [anon_sym_SLASH_EQ] = ACTIONS(85),
    [anon_sym_PERCENT_EQ] = ACTIONS(85),
    [anon_sym_AMP_EQ] = ACTIONS(85),
    [anon_sym_PIPE_EQ] = ACTIONS(85),
    [anon_sym_CARET_EQ] = ACTIONS(85),
    [anon_sym_PLUS] = ACTIONS(87),
    [anon_sym_DASH] = ACTIONS(87),
    [anon_sym_STAR] = ACTIONS(87),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_PERCENT] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(87),
    [anon_sym_GT] = ACTIONS(87),
    [anon_sym_EQ] = ACTIONS(87),
    [anon_sym_AMP] = ACTIONS(87),
    [anon_sym_PIPE] = ACTIONS(87),
    [anon_sym_CARET] = ACTIONS(87),
    [anon_sym_TILDE] = ACTIONS(85),
    [anon_sym_DOT] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(85),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_COMMA] = ACTIONS(85),
    [anon_sym_COLON] = ACTIONS(87),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hier(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hier",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
